# Generated by Django 2.1.1 on 2018-10-14 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('AP', 'Actualizacion Profesional'), ('FD', 'Formacion Docente'), ('DT', 'Diplomado en Tutorias'), ('DC', 'Diplomado en Competencias'), ('APD', 'Actualizacion Profesional y Formacion Docente')], default='', max_length=3)),
                ('semestre', models.CharField(choices=[('ago_dic', 'Ago - Dic'), ('ene_jun', 'Ene - Jun')], default='', max_length=20)),
                ('anno', models.IntegerField(blank=True)),
                ('dia_inicio', models.DateField(blank=True)),
                ('dia_final', models.DateField(blank=True)),
                ('hora_inicio', models.TimeField(blank=True)),
                ('hora_final', models.TimeField(blank=True)),
                ('salon', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('calificacion', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroCursos.Curso')),
            ],
            options={
                'verbose_name_plural': 'Historial',
                'db_table': 'Historial',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='', max_length=1)),
                ('nombramiento', models.CharField(choices=[('TC', 'Tiempo Completo'), ('3/4', '3/4'), ('1/2', '1/2'), ('PA', 'Por Asignatura'), ('HN', 'Honorarios'), ('HA', 'Horas Administrativas'), ('DIR', 'Directivo')], default='', max_length=3)),
                ('email', models.EmailField(default='', max_length=254)),
                ('grado', models.CharField(choices=[('lic', 'Licenciatura'), ('mtr', 'Maestria'), ('doc', 'Doctorado')], default='', max_length=4)),
                ('departamento', models.CharField(default='', max_length=20)),
                ('puesto', models.CharField(choices=[('docente', 'Docente'), ('jefe', 'Jefe Depto')], default='', max_length=7)),
                ('telefono_particular', models.IntegerField(blank=True, default='')),
                ('RFC', models.CharField(blank=True, default='', max_length=14)),
                ('CURP', models.CharField(blank=True, default='', max_length=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserProfile',
                'db_table': 'UserProfile',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='alumno',
            field=models.ManyToManyField(blank=True, related_name='alumno', through='registroCursos.Historial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='colaborador',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
