# Generated by Django 2.1.1 on 2018-09-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='curso',
        ),
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(to='registroCursos.Alumno'),
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
    ]
