# Generated by Django 2.1.1 on 2018-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
