# Generated by Django 2.1.1 on 2018-11-04 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registroCursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('pregunta_2', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('pregunta_3', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('pregunta_4', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('pregunta_5', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('pregunta_6', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('pregunta_7', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('pregunta_8', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('pregunta_9', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('pregunta_10', models.CharField(choices=[(5, 'Totalmente de Acuerdo'), (4, 'Parcialmente de Acuerdo'), (3, 'Indiferente'), (2, 'Parcialmente'), (1, 'Totalmente en Desacuerdo')], default='', max_length=2)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroCursos.Curso')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], default='', max_length=1),
        ),
    ]
