# Generated by Django 2.1.1 on 2018-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.CharField(choices=[('lic', 'Licenciatura'), ('mtr', 'Maestria'), ('doc', 'Doctorado')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='grado',
            field=models.CharField(choices=[('lic', 'Licenciatura'), ('mtr', 'Maestria'), ('doc', 'Doctorado')], max_length=4),
        ),
    ]
