# Generated by Django 2.1.1 on 2018-10-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nombramiento',
            field=models.CharField(choices=[('TC', 'Tiempo Completo'), ('3/4', '3/4'), ('1/2', '1/2'), ('PA', 'Por Asignatura'), ('HN', 'Honorarios'), ('HA', 'Horas Administrativas'), ('DIR', 'Directivo')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('AP', 'Actualizacion Profesional'), ('FD', 'Formacion Docente'), ('DT', 'Diplomado en Tutorias'), ('DC', 'Diplomado en Competencias'), ('APD', 'Actualizacion Profesional y Formacion Docente')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='historial',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
