# Generated by Django 2.1.1 on 2018-10-03 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0002_auto_20181002_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='nombramiento',
            field=models.CharField(choices=[('TC', 'Tiempo Completo'), ('3/4', '3/4'), ('1/2', '1/2'), ('PA', 'Por Asignatura'), ('HN', 'Honorarios'), ('HA', 'Horas Administrativas'), ('DIR', 'Directivo')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='instructor',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
