# Generated by Django 2.1.1 on 2018-11-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0002_auto_20181104_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuesta',
            options={'verbose_name_plural': 'Encuesta'},
        ),
        migrations.AlterModelTable(
            name='encuesta',
            table='Encuesta',
        ),
    ]
