# Generated by Django 2.1.1 on 2018-09-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0002_auto_20180927_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellidoPaterno',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='apellidoPaterno',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='nombre',
        ),
    ]
