# Generated by Django 2.1.1 on 2018-09-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0002_clase_is_passed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='is_passed',
            new_name='estaAprobada',
        ),
    ]
