# Generated by Django 2.1.1 on 2019-01-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0002_auto_20190116_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_1',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_10',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_11',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_2',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_3',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_4',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_5',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_6',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_7',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_8',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pregunta_9',
            field=models.CharField(choices=[('5', 'Totalmente de Acuerdo'), ('4', 'Parcialmente de Acuerdo'), ('3', 'Indiferente'), ('2', 'Parcialmente'), ('1', 'Totalmente en Desacuerdo')], default='', max_length=1),
        ),
    ]
