# Generated by Django 2.1.1 on 2019-03-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0003_auto_20190116_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='salon',
            field=models.CharField(default='', max_length=20),
        ),
    ]
