# Generated by Django 2.1.1 on 2018-09-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0003_auto_20180930_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='estaAprobada',
            new_name='aprobado',
        ),
    ]
