# Generated by Django 2.1.1 on 2018-09-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0004_auto_20180927_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroCursos.Alumno')),
            ],
            options={
                'db_table': 'curso_alumnos',
            },
        ),
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(through='registroCursos.Clase', to='registroCursos.Alumno'),
        ),
        migrations.AddField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroCursos.Curso'),
        ),
    ]
