# Generated by Django 2.1.1 on 2018-09-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroCursos', '0005_auto_20180930_1210'),
        ('registroCursos', '0004_auto_20180930_1154'),
    ]

    operations = [
    ]
